### ISSUE TITLE
No module named '__init__'

### ISSUE THREAD

**Issue by UedaTakeyuki** [UedaTakeyuki/getrpimodel#6]
python -m getrpimodel
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/pi/.pyenv/versions/3.12.3/lib/python3.12/site-packages/getrpimodel/__main__.py", line 2, in <module>
    import __init__ as getrpimodel
ModuleNotFoundError: No module named '__init__'

**Comment by UedaTakeyuki** [comment]
Fix line2 of __main__.py as follow:

old: import __init__ as getrpimodel
new: import getrpimodel.__init__ as getrpimodel

**Comment by UedaTakeyuki** [comment]
Fixed at version 0.1.25
